# Coding the single neuron
A single neuron needs :
1. Input
2. Weights
3. Bias
4. Activation function

In [1]:
# all values are for example
inputs = [1.0,2.0,3.0]
weights = [0.2,0.8,-0.5]
bias = 2.0

# output = input * weights + bias
outputs = inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias
print(outputs)

2.3


## Layer of neurons

We are implementing the fully connected neural network

In [3]:
# to code a layer with three neurons
inputs = [1.0,2.0,3.0,2.5]
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5
outputs = [
    inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1, # neuron 1
    inputs[0] * weights2[0] + inputs[1] * weights1[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2, # neuron 2
    inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3 # neuron 3
]

print(outputs)

[4.8, 4.63, 2.385]


In [5]:
# using for loop
inputs = [1.0,2.0,3.0,2.5]
weights = [[0.2, 0.8, -0.5, 1],[0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]
biases = [2,3,0.5]
output_neuron = []

for weight_neuron,bias in zip(weights,biases):
    output = 0
    for inp,weight in zip(inputs,weight_neuron):
        output += inp * weight
    output += bias
    output_neuron.append(output)

print(output_neuron)

[4.8, 1.21, 2.385]


## Single neuron in numpy

In [1]:
import numpy as np

inputs = np.array([1.0,2.0,3.0,2.5,])
weights = np.array([0.2, 0.8, -0.5, 1])
bias = 2.0

outputs = np.dot(inputs,weights) + bias
print(outputs)

4.8


## Layer in numpy

In [2]:
inputs = [1.0,2.0,3.0,2.5]
weights = [[0.2, 0.8, -0.5, 1],[0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]
biases = [2,3,0.5]
outputs = np.dot(weights,inputs) + biases # weights is passed first and then inputs are passed to get the list of dot products as result
print(outputs)

[4.8   1.21  2.385]


## Batches of data

Right now we only used one sample or observation. In real world we would use multiple data so we use batches. For each value in the feature observation datum `[1.0,2.0,3.0,2.5]`, together they form a **feature set instance** and also called **observation** or a **sample**

By training the model with batches provides the model to tweak the weights and bias and it will be generalized rather than being overfit.

`Numpy` as no direct method for matrix multiplication we use this new concept called `transpose`.

In [6]:
# matrix multiplication using Transpose
a = [1,2,3]
b = [4,5,6]
a = np.array([a])
b = np.array([b]).T

print(np.dot(a,b))

[[32]]


## Layer of neurons and batch of data with numpy

In [7]:
inputs = [[1.0,2.0,1.4,2.0],[3.0,1.2,4.1,3.2],[-2.5,2.3,6.6,5.3]]
weights = [[0.2, 0.8, -0.5, 1],[0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]
biases = [2,3,0.5]

outputs = np.dot(inputs,np.array(weights).T) + biases
print(outputs)

[[ 5.1    1.044  1.678]
 [ 4.71   2.874  2.877]
 [ 5.34  -1.277  6.262]]
